### ISSUE TITLE
Publish FinBIF Checklist 2024

### ISSUE THREAD

**Issue by laihoel** [luomus/meta#157]
- [x] Send heads up email for editors in October (Tea)
- [x] Download checklist's draft and compare it to checklist 2023, version 1 (Eppu, Esko)
- [x] Send email about checklist work for editors & experts in November (Eppu)
- [x] Download checklist's draft and compare it to checklist 2023, version 2 (Eppu, Esko)
- [x] Send reminder for editors (end of November) (Eppu)
- [x] Organize trainings for editors (Eppu, Tea)
- [x] Download checklist's draft and compare it to checklist 2023, version 3 (Eppu, Esko)
- [x] Check checklist for errors (Eppu)

- [x] Compile metadata (December) (Eppu)
- [x] Send metadata for editors to check (January) (Eppu)
- [x] Download checklist Jan 1. (Eppu)
- [x] Make comparison (Esko)
- [x] Calculate statistics (Eppu)
- [x] Fix errors in the checklist (Eppu)
- [x] Make cover (Eppu)
- [x] Update foreword & introduction (Eppu, Tea)
- [x] Edit metadata based on comments (Eppu)
- [x] Make the files to be published (Eppu)
- [x] Upload files to cdn.laji.fi (Esko)
- [x] Update page laji.fi/checklist + info.laji.fi (Eppu)
- [x] Write and publish news (Eppu, Emil)
- [x] Social media posts (Eppu, Emil)
- [x] Send Legal Deposit for National Library (Eppu)

**Comment by laihoel** [comment]
Files in BDI Unit Teams: General: https://helsinkifi.sharepoint.com/:f:/s/BDIUnit/Ejc-X8Zj2HZMri3GO_Y9VcYB9VIUUa2AefRoB78stE90Qw?e=z29Ahw

**Comment by esko-piirainen** [comment]
Last step: @wkmor1 will sent it to Checklist Bank
